apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: aws-account-shredder-template

parameters:
  - name: IMAGE
    required: true
    value: quay.io/app-sre/aws-account-shredder
  - name: IMAGE_TAG
    required: true
    value: latest
  - name : REPLICAS
    required: true
    value : "1"

objects:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: aws-account-shredder
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: aws-account-shredder
    rules:
      - apiGroups:
          - route.openshift.io
        resources:
          - routes
        verbs:
          - 'create'
          - 'get'
          - 'list'
          - 'watch'
          - 'update'
          - 'patch'
          - 'delete'
          - 'deletecollection'
      - apiGroups:
          - ""
        resources:
          - services
          - secrets
        verbs:
          - 'create'
          - 'get'
          - 'list'
          - 'watch'
          - 'update'
          - 'patch'
          - 'delete'
          - 'deletecollection'
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: aws-account-shredder
    subjects:
      - kind: ServiceAccount
        name: aws-account-shredder
    roleRef:
      kind: Role
      name: aws-account-shredder
      apiGroup: rbac.authorization.k8s.io
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: aws-account-shredder
      labels:
        name: aws-account-shredder
    spec:
      replicas: ${{REPLICAS}}
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 0
          maxSurge: 1
      selector:
        matchLabels:
          name: aws-account-shredder
      template:
        metadata:
          labels:
            name: aws-account-shredder
        spec:
          serviceAccountName: aws-account-shredder
          containers:
            - name: aws-account-shredder
              image: ${IMAGE}:${IMAGE_TAG}
              imagepullpolicy: Always
              resources:
                requests:
                  memory: "100Mi"
                limits:
                  memory: "2048Mi"
              env:
                - name: OPERATOR_NAME
                  value: "aws-account-shredder"
